apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: d4jn1r4r0-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/d4jn1r4r0-java-quarkus-gitops